[package]
name = "learning_shell_generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
serde = "1.0.196"
shell-escape = "0.1.5"
upon = "0.8.0"
